name: DeepSource Analysis
on:
  push:
    branches:
      - master  # Replace with your default branch if not 'main'
  pull_request:
    branches:
      - master  # Replace with your default branch if not 'main'

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run DeepSource analysis
      run: |
        # Install DeepSource CLI
        curl https://deepsource.io/cli | sh

        # Run DeepSource analysis
        ./bin/deepsource analyze
